services:

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    user: ${CUID:-0}:${CGID:-0}
    container_name: composer
    profiles:
      - create-project
      - delete-project
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - laravel-development

#  artisan:
#    image: php
#    container_name: artisan
#    networks:
#      - laravel-development

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - laravel-development

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    user: ${CUID:-0}:${CGID:-0}
    container_name: php-fpm
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./laravel-development
        target: /app
    depends_on:
      composer:
        condition: service_completed_successfully
        # following requires docker version not lower than 2.20.0
        required: false
    networks:
      - laravel-development

#  mysql:
#    image: mysql
#    container_name: mysql
#    networks:
#      - laravel-development

#  phpmyadmin:
#    image: phpmyadmin
#    container_name: phpmyadmin
#    networks:
#      - laravel-development

networks:
  laravel-development:
    name: laravel-development
    driver: bridge