services:

  composer:
    container_name: composer
    build:
      context: ./composer
      dockerfile: Dockerfile
    user: ${CUID:-0}:${CGID:-0}
    environment:
      TZ: ${TZ}
    profiles:
      - create-project
      - delete-development-environment
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - laravel-development

  artisan:
    container_name: artisan
    build:
      context: ./artisan
      dockerfile: Dockerfile
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    depends_on:
      composer:
        condition: service_completed_successfully
        required: false
    volumes:
      - type: bind
        source: ./laravel-development
        target: /app
    networks:
      - laravel-development

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    volumes:
      - type: bind
        source: ./nginx/conf.d
        target: /etc/nginx/conf.d
    networks:
      - laravel-development

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    user: ${CUID:-0}:${CGID:-0}
    restart: unless-stopped
    depends_on:
      composer:
        condition: service_completed_successfully
        required: false
    volumes:
      - type: bind
        source: ./laravel-development
        target: /app
    networks:
      - laravel-development

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
      MYSQL_DATABASE: laravel
      TZ: ${TZ}
    secrets:
      - mysql-root-password
    volumes:
      - laravel-development-mysql-data:/var/lib/mysql
    networks:
      - laravel-development

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      TZ: ${TZ}
    depends_on:
      - mysql
    networks:
      - laravel-development

secrets:
  mysql-root-password:
    file: ./secrets/mysql_root_password.txt

volumes:
  laravel-development-mysql-data:
    name: laravel-development-mysql-data

networks:
  laravel-development:
    name: laravel-development
    driver: bridge